name: Deploy Services to staging VM

on:
  push:
    branches:
      - staging

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: se-staging
    steps:
      - name: Update repositories
        run: |
          cd /var/www/front-end
          git fetch origin
          git reset --hard origin/staging

          cd /var/www/back-end
          git fetch origin
          git reset --hard origin/staging

          cd /var/www/api-gateway
          git fetch origin
          git reset --hard origin/staging

          cd /var/www/external-models
          git fetch origin
          git reset --hard origin/staging

          cd /var/www/export-service
          git fetch origin
          git reset --hard origin/staging

          cd /var/www/orchestration
          git fetch origin
          git reset --hard origin/staging
          
          cd /var/www/word-add-in
          git fetch origin
          git reset --hard origin/staging

      - name: Run Docker Compose
        run: |
          cd /var/www/orchestration
          docker-compose down
          docker-compose build
          export ENVIRONMENT=staging
          docker-compose up -d